print("hello work")
print("goodmorning")
print("ioane aris 9 wlis")
print("two")
print("hi")
print("nice")
print("go")
print("cherry")
print("tomato")
print("boy")
print("goa")
print("good")
print("print")
print("python")
print("bmw")
print("20")
print("gamarjobaa")
print("ok")
print("hello")
print("goa is best")



print("ჯერ არავინ გავიცანი")